05 serializer
Chernyshenko/made_2019_cpp pull request #1
Opened 2019-11-07 13:27 UTC by Chernyshenko

2019-11-07 17:38 UTC, smirnov-vs requested changes

2019-11-07 17:38 UTC, smirnov-vs commented on 05/serializer.hpp
> +    Error process(T&& val, Args&&... args)
цепочка форвардов не работает, изучаем еще раз этот момент

2019-11-07 17:38 UTC, smirnov-vs commented on 05/serializer.hpp
> +    Error deprocess(T&& val, Args&&... args)
аналогично

2019-11-10 15:47 UTC, smirnov-vs commented on 05/serializer.hpp
> +        out_ << val << Separator;
пока значение дойдет, к примеру, сюда, оно может скопироваться до 2 раз
надо еще подумать

2019-11-12 10:12 UTC, smirnov-vs approved these changes
Сейчас сериализатор принимает lvalue ссылки, затем передает её по цепочке как форвард ссылку, в этом смысла нет, цепочка работает неправильно. Вдобавок сериализатор не примет rvalue объекты, что может быть проблемой.
У десериализатора практически все также, только идеологически у него меньше смысла принимать rvalue объекты, только разве что игнорирования значения при парсинге.

Задачку закрываем, по желанию можно доделать до верного варианта, как выше

2019-11-12 12:28 UTC, Chernyshenko commented
Лекции про rvalue у нас еще не было, я доделаю после нее

2019-11-15 10:14 UTC, smirnov-vs approved these changes
привет!
да, все верно)

2019-11-19 14:29 UTC, merged