add hw 07 - format string
Chernyshenko/made_2019_cpp pull request #3
Opened 2019-11-26 13:48 UTC by Chernyshenko

2019-11-26 14:46 UTC, smirnov-vs requested changes

2019-11-26 14:46 UTC, smirnov-vs commented on 07/format.hpp
> +    return format_argv(std::forward<std::string>(s), argv);
привет!
форвард используется для идеальной передачи с форвард ссылками
для перемещения мув

2019-11-26 14:46 UTC, smirnov-vs commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
что если формат строка lvalue?

2019-11-27 09:54 UTC, Chernyshenko commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
Можно сделать перегрузку с std::string& s
Или стоит делать через шаблон вместо string?

2019-11-27 10:02 UTC, Chernyshenko commented on 07/format.hpp
> +    return format_argv(std::forward<std::string>(s), argv);
Не понял, зачем тут move? для argv?

2019-11-28 08:10 UTC, smirnov-vs commented on 07/format.hpp
> +    return format_argv(std::forward<std::string>(s), argv);
`std::forward<std::string>(s)`
здесь используется форвард без форвард ссылки, это неверно

2019-11-28 08:13 UTC, smirnov-vs commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
`std::string& s`
это считается плохим тоном, мы уже это проходили, вспомнить возможные решения можно по 6 лекции

2019-11-28 08:13 UTC, smirnov-vs commented on 07/format.hpp
> +std::string format_argv(String&& s, std::vector<std::string>& argv){
надо сделать без шаблона

2019-11-28 08:14 UTC, smirnov-vs commented on 07/format.hpp
> +            int argi = IntFromChar((char*)(&s[i]), j);
const cast запрещен

2019-11-28 10:12 UTC, Chernyshenko commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
Ну, можно еще использовать move при вызове format, но вряд ли мы хотим так делать.
А так - если не создавать перегрузку, то там только вариант с template

2019-11-28 10:37 UTC, smirnov-vs commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
что насчет const&?

2019-11-28 11:02 UTC, Chernyshenko commented on 07/format.hpp
> +std::string format(std::string&& s, T&& val, Args&&... args){
Да, не обратил на это внимания. 
переделал

2019-12-11 22:18 UTC, smirnov-vs commented on 07/format.cpp
> +std::string format_argv(const std::string&& s, std::vector<std::string>& argv){
const rvalue ссылка?

2019-12-11 22:18 UTC, smirnov-vs commented on 07/format.cpp
> +std::string format_argv(const std::string&& s, std::vector<std::string>& argv){
это надо пофиксить

2019-12-11 22:18 UTC, smirnov-vs approved these changes
привет!
задачу закрыл

2019-12-12 08:14 UTC, Chernyshenko commented on 07/format.cpp
> +std::string format_argv(const std::string&& s, std::vector<std::string>& argv){
поменял

2019-12-12 09:15 UTC, merged