08
Chernyshenko/made_2019_cpp pull request #5
Opened 2019-12-12 09:21 UTC by Chernyshenko

2019-12-13 10:24 UTC, smirnov-vs requested changes

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +    : public std::iterator<std::bidirectional_iterator_tag, T>
не та категория

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
слева мусор, так делать нельзя

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +    std::fill(data, data + size_, defaultValue );
аналогично

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +            data[i] = T();
и тут

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +void Vector<T, Alloc>::push_back(value_type&& value){
работает неправильно

2019-12-13 10:24 UTC, smirnov-vs commented on 08/Vector.hpp
> +        data[i].~T();
этим занимается аллокатор

2019-12-13 13:04 UTC, Chernyshenko commented on 08/Vector.hpp
> +    : public std::iterator<std::bidirectional_iterator_tag, T>
категория тэга итератора? или о чем речь?

2019-12-13 13:05 UTC, smirnov-vs commented on 08/Vector.hpp
> +    : public std::iterator<std::bidirectional_iterator_tag, T>
Да, она

2019-12-13 13:08 UTC, Chernyshenko commented on 08/Vector.hpp
> +    : public std::iterator<std::bidirectional_iterator_tag, T>
ага, увидел что там рандом аксесс должен быть

2019-12-13 13:11 UTC, Chernyshenko commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
Мусор в data если там до этого ничем не заполнили?

2019-12-16 15:43 UTC, smirnov-vs commented on 08/Vector.hpp
> +    : public std::iterator<std::bidirectional_iterator_tag, T>
теперь итератор не подходит под свою категорию

2019-12-16 15:44 UTC, smirnov-vs commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
да, надо с этим как то жить и написать шаблоны правильно

2019-12-16 17:02 UTC, Chernyshenko commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
std::move тоже не годится?

2019-12-16 17:18 UTC, smirnov-vs commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
Нет, там же сырая память

2019-12-16 17:25 UTC, Chernyshenko commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
как-то проверять поэлементно?

2019-12-16 17:26 UTC, smirnov-vs commented on 08/Vector.hpp
> +    std::copy(data, data + size_, mem);
Нужно не гадать, а почитать материалы, спросить коллег 
Не мне же это исправлять и потом поставить баллы

2019-12-23 09:46 UTC, smirnov-vs approved these changes
привет!
основные моменты с аллокатором теперь верно сделаны, я закрою задачку

2019-12-23 09:46 UTC, smirnov-vs commented on 08/Vector.hpp
> +void Vector<T, Alloc>::push_back(value_type&& value){
этот метод все еще работает неверно)

2019-12-28 08:58 UTC, merged